### ISSUE TITLE
Cannot "choose private key"

### ISSUE THREAD

**Issue by florentc** [kknickkk/Spider#1]
Hello, I am trying to connect to a remote host using an openssh private key. After I browse my local filesystem and select the id file, it does not seem to be taken into account. There is no visible change in the gui and pressing "connect" results in an error: "Could not connect".

I am running Spider version 0.2.0 from fdroid under Lineage 16.

**Comment by nickdurante** [comment]
Hi, is the key in the PEM format?
It should start with:
`-----BEGIN RSA PRIVATE KEY-----`

The key is generated like this:
`ssh-keygen -p -f .ssh/id_rsa -m pem -P "" -N ""`

You can also convert it using:
`ssh-keygen -f my-rsa-key -m pem -p`

Anyway I'll put a check when parsing the key, mind you the app is still in testing phase

**Comment by nickdurante** [comment]
Should be fixed with [1aceb14](https://github.com/nickdurante/Spider/commit/1aceb14a7ca1251f49eb1d7a8173c275eccb0154)

**Comment by florentc** [comment]
You were right, I was using the new default openssh key format. Converting to PEM solved the issue. Thank you for your help and quick reply.
