### ISSUE TITLE
Application shuts down when "port" is empty

### ISSUE THREAD

**Issue by florentc** [kknickkk/Spider#2]
In Spider version 0.2.0 from fdroid, on Lineage 16, when the "connect" button is pressed and the "port" field is empty, the application shuts down.

**Comment by nickdurante** [comment]
Hi again :), 
I can't reproduce the error, could you append a logcat?

**Comment by florentc** [comment]
Here is the output: https://gist.github.com/florentc/9f15fc4dd0b6f4b6fccdcde0c323d433
I just clicked on "connect" without filling up any of the fields. According to previous tries, only the "port" field triggers the crash.

**Comment by nickdurante** [comment]
Should be fixed with [1aceb14](https://github.com/nickdurante/Spider/commit/2fb3a8fb53d05d820f8050cee049226613ad9252).

I'm releasing v0.2.1 to include these fixes.

**Comment by florentc** [comment]
Thank you! This indeed solves the issue.
