### ISSUE TITLE
Spider on Google Play Store

### ISSUE THREAD

**Issue by gdluca** [kknickkk/Spider#4]
Hi,

do you have any plans on releasing Spider on the Play Store?
I would like to use it on Android for ChromeOS and I cannot sideload apk on Stable Channel(Dev channel should work, but prefer Stable).

Thanks!

**Comment by nickdurante** [comment]
Hi,
At the moment I haven't planned to release the app on the Play Store, but I'll think about it.

**Comment by gdluca** [comment]
Ok, thank you!
