### ISSUE TITLE
(Request for enhancement?) Support passphrase-encrypted private keys

### ISSUE THREAD

**Issue by jaimet** [kknickkk/Spider#5]
Am I correct in thinking that spider does not (currently) support passphrase-encrypted private keys? If so, can I please request supporting passphrase-encrypted private keys as an enhancement?

Thank you.

**Comment by nickdurante** [comment]
Yes at the moment it doesn't support it, but I'll try to find the time to implement this feature. 

I'll keep this thread updated

**Comment by nickdurante** [comment]
Latest release v0.2.2 now implements your feature, it should appear on F-Droid in a couple of days

**Comment by nickdurante** [comment]
v0.2.2 is now on F-Droid, closing thread.
